Initial (basic) Behavior Designer integration
YondernautsGames/NeoFPS_BehaviorDesigner pull request #1
Opened 2020-03-11 05:07 UTC by rgardler

2020-03-11 23:14 UTC, YondernautsGames requested changes

2020-03-11 23:14 UTC, YondernautsGames commented on Scripts/IsAlive.cs
> +                if (currentGameObject != null)
Should set healthManager to null if this fails

2020-03-11 23:14 UTC, YondernautsGames commented on Scripts/IsAlive.cs
> +            if (healthManager.isAlive)
Need a null check against healthManager. Should this mean defaults to success or failure?

2020-03-11 23:14 UTC, YondernautsGames commented on Scripts/DamageSource.cs
> +            get { return transform.name + "inflicts damage of " + damageAmount; }
Description should just be a descriptive name (eg character name). It's up to the logger to format it in place

2020-03-12 03:41 UTC, rgardler commented
Thanks @YondernautsGames, these are pretty trivial (and resolved) so I'll go ahead and merge without further review.

2020-03-12 03:42 UTC, merged